### ISSUE TITLE
Add AArch64 builds

### ISSUE THREAD

**Issue by mcgordonite** [thefrontside/ctrlc-windows#46]
It would be awesome to get AArch64 (arm64) support.

The package seems to work without modification when built on an arm64 Windows system. The challenge would be distribution for multiple platforms. The napi-rs docs suggest publishing multiple packages for this: https://napi.rs/docs/introduction/getting-started#deep-dive.

Would you be open to a PR?

**Comment by mcgordonite** [comment]
Hi @cowboyd @jbolda @minkimcello, would you be open to a PR for this? Thanks!

**Comment by jbolda** [comment]
Thanks for the ping, missed this! We originally opted for a single package as it was only a single binary for a single platform. I would be happy to support a PR supporting ARM on Windows.

I agree that following the recommended napi approach would then be appropriate. We would be publishing 3 packages, the root `ctrlc-windows` and then an optional dep for each of x86 and arm64. Does that match your expectations?

**Comment by mcgordonite** [comment]
That's right, there could be three packages: `ctrlc-windows`, `ctrlc-windows-x64` and `ctrlc-windows-arm64`. I'll have a go at restructuring this repo along those lines and put up a PR.

**Comment by mcgordonite** [comment]
@jbolda I found a simpler solution in the end, let me know what you think: https://github.com/thefrontside/ctrlc-windows/pull/47

**Comment by mcgordonite** [comment]
Thanks for merging my PR. Is it possible to do a release including the change?

**Comment by cowboyd** [comment]
@mcgordonite released! https://github.com/thefrontside/ctrlc-windows/pull/49

**Comment by mcgordonite** [comment]
Thanks @cowboyd, this is working for both architectures now.
